services:
  postgres:
    image: postgres:15-alpine
    container_name: ordefin-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./src/main/java/com/ordenfinapi/infra/postgre/init.sql:/docker-entrypoint-initdb.d/init.sql

