version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: ordefin-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  redis:
#    image: redis:7-alpine
#    container_name: ordefin-cache
#    restart: always
#    ports:
#      - "${REDIS_PORT}:6379"

volumes:
  postgres_data: